spring:
  data:
    mongodb:
      uri: ${MONGO_ATLAS_HML_URI}

application:
  auth:
    expose-reset-preview: false
    expose-session-token: true
    cookie:
      secure: true
      same-site: None
  hml:
    access:
      enabled: ${APP_HML_ACCESS_ENABLED:true}
      allowed-emails: ${APP_HML_ALLOWED_EMAILS:}
